# Generated by Django 5.1.2 on 2024-10-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_insight_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
