# Generated by Django 5.1.2 on 2024-10-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_insight_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
