# Generated by Django 5.1.2 on 2024-10-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_insight_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='likelihood',
            field=models.IntegerField(blank=True, max_length=255),
        ),
    ]
