# Generated by Django 5.1.2 on 2024-10-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_insight_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
