# Generated by Django 5.1.2 on 2024-10-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_insight_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
