# Generated by Django 5.1.2 on 2024-10-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_insight_relevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='pest_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='swot_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
