# Generated by Django 5.1.2 on 2024-10-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_pest_field_insight_pestle_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insight',
            old_name='pestle_field',
            new_name='pestle',
        ),
    ]
